language: node_js
node_js:
    - "node"
cache:
  directories:
    - node_modules
after_success: npm version patch
deploy:
  skip_cleanup: true
  provider: npm
  email: tnl.disposal.box+npmjs@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    repo: letsrock-today/mock-local-storage
