language: node_js
node_js:
    - "node"
cache:
  directories:
    - node_modules
deploy:
  skip_cleanup: true
  tag: next
  provider: npm
  email: tnl.disposal.box+npmjs@gmail.com
  api_key: $NPM_TOKEN
  on:
    # tags: true # seams to conflict with `tag: next`
    repo: letsrock-today/mock-local-storage
